#ifndef __DIANRU_OBCODE_H__
#define __DIANRU_OBCODE_H__
#define getDianruDeviceOrientation getKillWeed
#define setDianruRequestLaseTimeWithUrl setQueryView
#define dianruViewload CatchSpider
#define dianruStartEGOUpdate InviteEgg
#define dianruSpendScoreResultCallback AnswerRice
#define getDianruMainBounds getCatchTabBar
#define dianruObjectForKey MakeKilometer
#define YQL_V PermitCountry
#define dianruFindview DecorateNoodles
#define getDianruAppId getDanceCarrot
#define YQLHttpActionExecer ShowTable
#define YQLTextField BlowBear
#define YQLAlignCenter HoldWindow
#define dianruWithMySelf PermitParrot
#define dianruNewCheckSum CallActivityView
#define YQLANIMATION_TYPE ApendCarrot
#define dianruQueryString PrintChicken
#define dianruResizeToFit NextTree
#define YQLMacros WaitSegment
#define dianruReadLocationFor AddTabBar
#define dianruEnable FowardSnake
#define dianruRequestBlock StartWithInterest
#define dianruImageFor LoadActivityView
#define dianruTimeout CompileForest
#define YQLTextureInfo HashView
#define dianruExpire LockCache
#define YQLViewUnknow ApendLiberty
#define dianruParseEvent LookFlower
#define dianruParseFloat CatchWebView
#define YQLTextureVertical DoWebView
#define YQLReqestResultType DanceBread
#define YQLViewCell ParseLiberty
#define getDianruSpendScore getMatchEgg
#define YQLTextureHorizontal CallCountry
#define dianruShareIstance CoverTableViewCell
#define dianruDidJumped BlowWhale
#define dianruActions AnswerParrot
#define dianruBuildWithName ProductCell
#define YQLRunningProcess BiteSnake
#define YQLSetAction BeatVoice
#define YQLCodeAction RunAchieve
#define setDianruNode setBuildRadish
#define dianruDuration CatchPotato
#define YQLNotificationAction StartWithSpider
#define dianruDidViewDestroy CoverTabBar
#define dianruExec BeatPiano
#define dianruApplicationKey RunWindow
#define dianruLoadView CostLaugh
#define addDianruStyle NextCell
#define dianruRequestSpace CollectLiberty
#define dianruCreate SleepPicker
#define dianruContext PermitKilometer
#define dianruCancel CrashLiberty
#define YQLAlignLeft CompilePotato
#define YQLViewText CloneAlertView
#define initWithDianruContext initHoldView
#define dianruName ProductVoice
#define dianruParseTextAttr DevelopPumpkin
#define getDianruMacAddress getDanceButton
#define setDianruArrowData setPutFlower
#define YQLHttpRequest FallDamage
#define dianruSubview ServeTrumpet
#define setDianruDelegateNull setBrushForest
#define dianruDidClicked CompileCake
#define getDianruWifiIP getSetDessert
#define dianruReadNetDataTaskFor CutTableViewCell
#define dianruStopLoadAnimation FallActivityView
#define YQLViewTextField RunWeed
#define dianruFsPath SetPiano
#define dianruRunningProcesses HashSnake
#define dianruEnableUseRadius MakeAlertView
#define YQLBeginAction ServeRice
#define YQLActionNode SleepFeature
#define dianruWakeup SleepCache
#define YQLFontBold StudyWebView
#define YQLViewSection BrushTree
#define YQLUrlCache GeneralAlertView
#define dianruEngine LookImage
#define dianruMovieFinishedCallback CatchBroccoli
#define YQLViewSimple CloneForest
#define dianruLoadData CrashImage
#define dianruHide ChangeForest
#define dianruRemove DevelopCake
#define dianruResult borrowFeature
#define YQLFontStyle_ALL NextFeature
#define YQLViewDelegate LoadBread
#define refreshDianruTableHeaderDidTriggerRefresh DoExperience
#define dianruJump FallMemory
#define dianruRect CatchParrot
#define dianruAutoresize ProductTable
#define dianruStartRotation ServeCountry
#define YQLViewTable PrintPlant
#define addDianruChild QueryPicker
#define dianruPurge LockTableCell
#define getDianruFreeSpace getCompileNoodles
#define YQLOPullRefreshLoading GeneralNoodles
#define YQLHttpAction ChangeCountry
#define dianruText MakeWhale
#define dianruImage ChangeFeature
#define _dianruBuild PermitAlertView
#define setDianruImageWithContent setBlowLaugh
#define dianruInitialize DecorateCache
#define YQLRefreshTableHeaderDelegate IteratorPotato
#define dianruExecuteAnimation StartWithPicker
#define getDianruLocation getMakeBear
#define dianruMD5Hash PutDamage
#define setDianruResult setBorrowFeature
#define YQLSectionView PrintRadish
#define dianruStopEGOUpdate AnswerChicken
#define YQLFontDELETE BeatNoodles
#define refreshDianruScrollViewDidEndDragging CostFeature
#define dianruTimes PermitCache
#define dianruDidViewClose DevelopDolphin
#define dianruParent AddTrumpet
#define dianruHandleSingleFingerEvent CloneCell
#define YQLNode WaitAdvice
#define YQLScriptRunner WaitSlider
#define YQLAnimationView KillDessert
#define YQLViewAnimation ChangeActivityView
#define dianruTarget StudyDamage
#define getDianruQueryString getWaitSpider
#define getDianruReportUrl getCollectButton
#define dianruParseActionNode StudyPotato
#define dianruUpdateContent DevelopWebView
#define dianruCutStr GetBroccoli
#define dianruCheckSum SleepInterest
#define getDianruWifiInfo getBlowInterest
#define setDianruRefreshArrowImage setCutAlertView
#define getDianruScore getProductBelieve
#define YQLMediaView EndWithTree
#define refreshDianruTableHeaderDataSourceIsLoading KillPumpkin
#define YQLTexture MatchCache
#define YQLViewInterstitial CostAchieve
#define dianruUrl PermitBread
#define dianruLocalIPAddress CloneSpider
#define refreshDianruScrollViewDataSourceDidFinishedLoading RunTomato
#define dianruAnis CreateToolBar
#define dianruWebViewCallBack LookToolBar
#define dianruDataFor DoBelieve
#define YQLDelegate HoldInterest
#define dianruFsDirectory ParsePlant
#define dianruEncryptWithText CollectTable
#define setDianruState setRunSwitch
#define dianruDecodeToUrl FallVoice
#define dianruLocation permitWindow
#define YQLTextureType CreateLaugh
#define getDianruFingerprint getDanceTabBar
#define dianruEvent BeatSlider
#define YQLViewHtml PutImage
#define YQLOPullRefreshPulling BlowTree
#define dianruExit MatchTabBar
#define dianruParseBackground InviteBelieve
#define YQLViewRoot MaintainForest
#define YQLAction ReplaceLiberty
#define YQLFactory KillDamage
#define YQLDeleteAction LoadMemory
#define YQLOrientation GeneralTable
#define dianruDiskInfo StudyAchieve
#define dianruDeviceOrientationDidChange MakeBroccoli
#define YQLTextureSimple PrintExperience
#define getDianruImage getLoadSwitch
#define dianruRun ApendNoodles
#define dianruWrite DevelopTomato
#define YQLInterstitialView BorrowParrot
#define dianruURLEncodedString HoldCache
#define dianruAppuserid EndWithAdvice
#define dianruExecOne IteratorRadish
#define YQLViewAction BeatExperience
#define getDianruMachineName getCatchRadish
#define dianruShowLoadAnimation LookCake
#define dianruKeyForString CloneCake
#define dianruWithData ReplaceKilometer
#define dianruMoviePlayerLoadStateChanged CostSnake
#define dianruFrame studyTableViewCell
#define YQLSimpleView CoverDolphin
#define YQLUIModel PrintDessert
#define dianruDeviceString BorrowWhale
#define dianruCreateWithView SleepTable
#define dianruShow CallDessert
#define dianruOn ReadPicker
#define dianruReportData StudyOnion
#define YQLIfAction MakeLabel
#define dianruParseHex InviteSlider
#define dianruCacheTimeList CloneAdvice
#define YQLScript CrashSegment
#define dianruHTTPResultCallback DanceToolBar
#define dianruScoreResultCallback CreateCake
#define dianruKeychainIdfa RunPlant
#define getDianruTimestamp getProductAlertView
#define dianruSuspend CloneBread
#define dianruDelegate RunVoice
#define dianruWithRequst MatchLiberty
#define dianruWithUrl CreateCountry
#define dianruHash WaitMemory
#define getDianruDevicesFamily getLockWeed
#define getDianruOSVersion getReadKilometer
#define dianruStartAni BeatPotato
#define YQLView EndWithMemory
#define YQLFontStyleNode FindImage
#define dianruStopRotation LockTree
#define dianruDisposeContent IteratorSwitch
#define dianruWithCallback ComparePiano
#define dianruFindView DoLiberty
#define dianruURLDecodedString IteratorForest
#define YQLViewNode CostVoice
#define YQLTextureLoop CompareBread
#define getDianruUserId getCatchKilometer
#define dianruNode buildRadish
#define dianruStopAnimation MatchDamage
#define dianruUrlToDecode CatchVoice
#define dianruParseInsets InviteFlower
#define dianruKeychainMac BuildWeed
#define YQLAlign CatchMemory
#define dianruRegistClickEvent MakeTableViewCell
#define YQLViewLoader BorrowTabBar
#define refreshDianruScrollViewDidScroll ReplaceImage
#define YQLTextView StartWithButton
#define YQLEncryptUtil CallPumpkin
#define YQLViewUtil CallSubject
#define YQLRefreshTableView_LastRefresh ShowWebView
#define dianruString2Hex BorrowPotato
#define YQLLabelUpdate HashWhale
#define dianruView LookSpider
#define YQLCheckSum PutTableViewCell
#define YQLFontNormal FallSlider
#define dianruDecryptWithText GeneralBelieve
#define YQLContext ChangeTabBar
#define dianruSysctlbynameFctn StartWithDessert
#define YQLGTMBase64 ChangeDessert
#define dianruParseStyleAttr ProductCache
#define YQLOPullRefreshNormal FowardDessert
#define YQLKey MakeTable
#define YQLFontUnderLine NeedFlower
#define YQLSdkInfo MatchActivityView
#define dianruContent cloneSubject
#define setDianruContent setCloneSubject
#define dianruData AddSwitch
#define dianruForKey ParseLaugh
#define getDianruScreenFrame getRunCache
#define dianruLayer SetPumpkin
#define dianruClose DeleteFlower
#define dianruCode SetLabel
#define refreshDianruLastUpdatedDate IndexTomato
#define getDianruHttpFail getNextTable
#define dianruImageResultCallback FindPumpkin
#define YQLViewType MatchRadish
#define YQLTableCell GeneralRadish
#define YQLCacheRequest CatchDamage
#define dianruDecode ProductChicken
#define getDianruDiskid getCompareChicken
#define YQLStyleNode PrintParrot
#define YQLEngine ShowMemory
#define dianruScreenRotation DoBroccoli
#define getDianruKey getLockAlertView
#define dianruEnableRequestWithUrl FindRice
#define YQLTextureFull InvitePicker
#define YQLOpenAction BrushSnake
#define YQLViewFactory CoverForest
#define YQLBorder EndWithSlider
#define YQLFileSystem ReadOnion
#define dianruIsModify AddActivityView
#define dianruCenter GeneralSlider
#define YQLViewImage CompareImage
#define YQLDeviceInfo MaintainNoise
#define dianruParseStyle FindCountry
#define YQLFontStyle CollectTabBar
#define setDianruLocation getPermitWindow
#define dianruParseBorder CollectSubject
#define dianruParseView ShowCake
#define dianruFormat CompareMemory
#define dianruObject QueryFlower
#define YQLAlignRight GeneralSegment
#define dianruKey MatchNoise
#define dianruMasks BiteDessert
#define YQLRefreshTableHeaderView SleepTomato
#define dianruPadding ChangeSnake
#define dianruMethod StudyLiberty
#define refreshDianruTableHeaderDataSourceLastUpdated IndexActivityView
#define dianruSpaceUrl SleepCarrot
#define dianruWith StartWithDolphin
#define dianruDrawType MaintainImage
#define dianruLocalWiFiAvailable QuerySegment
#define dianruSubviews NextSpider
#define YQLPullRefreshState FunctionWhale
#define dianruLoadani StartWithAlertView
#define getDianruWithIDFA getFunctionSubject
#define dianruParseRect FindInterest
#define dianruParseColor CatchCake
#define dianruTimerAction StartWithView
#define YQLEndAction ShowSlider
#define dianruTo FunctionCountry
#define dianruLoad HashTableCell
#define getDianruWifiSSID getApendWindow
#define YQLTextFieldBri NextLiberty
#define dianruDidDataReceived CollectCake
#define dianruParseAlign KillExperience
#define YQLHtmlView ApendParrot
#define dianruDecodeOne BorrowNavigationBar
#define dianruBuild QueryPumpkin
#define addDianruEvent DevelopTable
#define dianruChecksum3 DecorateImage
#define dianruAddCallback ShowSubject
#define dianruChecksum2 CatchExperience
#define dianruChecksum1 StudySegment
#define dianruBind InviteBread
#define dianruDrawTexture BuildImage
#define setDianruImageWithUrl setAnswerTomato
#define isDianruJailbroken HashCache
#define getDianruBaseUrl getIteratorOnion
#define dianruValue InviteInterest
#define dianruCarrierName PrintCell
#define dianruSubType GeneralLiberty
#define YQLTableView LookWindow
#define dianruParseFontStyle StudyToolBar
#define YQLViewMedia DecorateExperience
#define dianruClearup MaintainPlant
#define dianruState runSwitch
#define YQLAlertAction CutInterest
#define dianruDidViewOpen IteratorParrot
#define dianruCloseMain FallNavigationBar
#define dianruDidReported EndWithProgress
#define dianruType CompileBear
#define dianruParseConf LookRice
#define YQLUtil ChangeDolphin
#define YQLEventManager CallCake
#define setDianruViewNode setCrashAlertView
#define setDianruFrame setStudyTableViewCell
#define YQLAnimationAction NeedNoise
#define dianruCallback CallSpider
#define YQLDataCache NextTabBar
#define YQLLoader DoNavigationBar
#define dianruStartAniType KillLabel
#define YQLOpenUDID HoldMemory
#define YQLLocation CrashTomato
#define YQL_H SleepProgress
#define dianruUpdate MaintainButton
#define dianruParseViewType DoImage
#define dianruStartAnimation IndexWindow
#define YQLImageView ChangeView
#define YQLSDK ReplacePiano
#define YQLWebView FunctionDolphin
#define dianruParseTextureType CreateMemory
#define dianruRequest FowardInterest
#define dianruExecIfElse DeleteBear
#define dianruCheckIsNeedModify QueryNoise
#define getDianruDiskTotalSpaceEx getInviteAlertView
#define dianruFileIsExists AnswerFlower
#endif /*__DIANRU_OBCODE_H__*/
